//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfBookshop
{
    using System;
    using System.Collections.Generic;
    
    public partial class book
    {
        public book()
        {
            this.wishlists = new HashSet<wishlist>();
        }
    
        public int bookID { get; set; }
        public string name { get; set; }
        public string author { get; set; }
    
        public virtual ICollection<wishlist> wishlists { get; set; }
    }
}
