//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfBookshop
{
    using System;
    using System.Collections.Generic;
    
    public partial class post
    {
        public int postID { get; set; }
        public System.DateTime dataPublished { get; set; }
        public string title { get; set; }
        public string body { get; set; }
    }
}
