//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfBookshop
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.wishlists = new HashSet<wishlist>();
        }
    
        public int userID { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string role { get; set; }
    
        public virtual ICollection<wishlist> wishlists { get; set; }
    }
}
