//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfBookshop
{
    using System;
    using System.Collections.Generic;
    
    public partial class wishlist
    {
        public int wishID { get; set; }
        public int IDuser { get; set; }
        public int IDbook { get; set; }
    
        public virtual book book { get; set; }
        public virtual user user { get; set; }
    }
}
